### ISSUE TITLE
Hi LanternD

### ISSUE THREAD

**Issue by randomwangran** [LanternD/.emacs.d#1]
I found the your blog is interesing and I am one of your long-timer reader.

I also find that you are a emacs user, and possible a user who visit emacs-china.org.

I think you are an expert in 电子工程.

[I would like introduce you to the Emacs family.](https://emacs-china.org/t/topic/3374/7?u=emacs_ran)

Are you okay with it?

**Comment by LanternD** [comment]
@randomwangran Oh my! Haven’t noticed the issue here. I am totally fine with your introduction (still on the way to be an expert though). Thanks a lot! 

However, I’m using another private dotfiles repo to keep track of my `.spacemacs.d` for quite a while. Maybe I would sync the configs here later.

Thanks!

**Comment by LanternD** [comment]
The emacs-china user link should be https://emacs-china.org/u/LanternD usually I just watch posts without commenting on it.
